{% set name = "aiida-vasp" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiida-vasp-{{ version }}.tar.gz
  sha256: 5167ce1d9aba75bcdd5df770b2fcc632f46a95bb4028b44b4f49fcf42a28e03c

build:
  entry_points:
    - mock-vasp = aiida_vasp.commands.mock_vasp:mock_vasp
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - reentry
  run:
    - aiida-core.atomic_tools >=1.2.1,!=1.4.0,!=1.4.1
    - lxml
    - packaging
    - parsevasp >=2.0.1
    - pymatgen <=2020.12.3
    - python >=3.6
    - subprocess32

test:
  imports:
    - aiida_vasp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aiida-vasp/aiida-vasp
  summary: AiiDA Plugin for running VASP calculations.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjsewell
