{% set name = "aiida-vasp" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 84221019608555450232907fb405a57b933556e96e79cf8637cdf11632d70982

build:
  entry_points:
    - mock-vasp = aiida_vasp.commands.mock_vasp:mock_vasp
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - aiida-core.atomic_tools~=2.4
    - lxml
    - packaging
    - parsevasp~=3.2

test:
  imports:
    - aiida_vasp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aiida-vasp/aiida-vasp
  summary: AiiDA Plugin for running VASP calculations.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mbercx
    - chrisjsewell
