{% set name = "aiida-vasp" %}
{% set version = "3.0.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 61caeb5c5d156af30b8b1fcf9e96fea468ad1d8dc3f6b3280ff96b88e1a7d391

build:
  entry_points:
    - mock-vasp = aiida_vasp.commands.mock_vasp:mock_vasp
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=3.4,<4
  run:
    - python >={{ python_min }}
    - aiida-core.atomic_tools ~=2.4
    - lxml
    - packaging
    - parsevasp ~=3.2

test:
  imports:
    - aiida_vasp
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/aiida-vasp/aiida-vasp
  summary: AiiDA Plugin for running VASP calculations.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
  - mbercx
  - chrisjsewell
