{% set name = "aiida-vasp" %}
{% set version = "4.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3dbad7699ee375723fbe8bb66ed85b533b612ce9d4ea7ec730e5a17ef41593b7

build:
  entry_points:
    - mock-vasp = aiida_vasp.commands.mock_vasp:mock_vasp
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=3.4,<4
  run:
    - python >={{ python_min }}
    - aiida-core >=2.3
    - ase
    - lxml
    - seekpath
    - packaging
    - pydantic
    - parsevasp >=3.2

test:
  imports:
    - aiida_vasp
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/aiida-vasp/aiida-vasp
  summary: AiiDA Plugin for running VASP calculations.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - mbercx
    - chrisjsewell
